### PR TITLE
AZERTY french keyboard

### PR DESCRIPTION
**Pull request by CHiPs44**
I didn't test it, it just builds.

### CODE REVIEW

**Comment by rumbledethumps** [comment]
Untested? There's a config option "RP6502_KEYBOARD" in CMakeLists.txt.

**Comment by CHiPs44** [comment]
I don't own any PicoComputer hardware for now, only 2 Picos, 1 Pico W and a VGA demo board.

I'm trying to figure out how to test this, and spent my sunday afternoon struggling with picoprobe and openocd just to know I need another Pico or a Pico Debug Probe, that's why this PR is WIP.

**Comment by rumbledethumps** [comment]
Ahh, that's unexpected but certainly explains my wonder. You don't need a debugger for light development like this. But you do need a Picocomputer (or most of one).

**Comment by CHiPs44** [comment]
I finally managed to test RIA alone with a serial to USB converter and our good old friend minicom, and corrected a few mistakes.

Every Unicode char gives an `?`.

Numpad 9 with Shift still gives 9 which is incorrect.

**Pull request closed without merging**
